# Generated by Django 4.1 on 2022-08-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
